# set-option(set):
#    -g : global option. all sessions
#         - This is the basic choise
#    -w : window option. a specific window
#    -s : session option. server (socket) scope
#         - Used when you provide a different socket with `tmux -L`
#         - Most users won't use this feature
#    -gw: global window option. all windows
#         - Use this for window-related options
#    -p : a specific pane
# NoFlag: a specific session

set-option -g mouse on
set-option -sg escape-time 1
set-option -sg repeat-time 100
set-option -g history-limit 5000

set-option -g default-terminal "screen-256color"
set-option -as terminal-overrides ",xterm-color:Tc"

set-option -g prefix C-q
unbind-key C-b

# bind-key(bind):
#   -T root / -n : global key binding without prefix
#   -N : description for the key binding
#   -r : repeatable key binding. 


bind-key -N "ウィンドウを垂直に分割" | split-window -h -c '#{pane_current_path}'
bind-key -N "ウィンドウを水平に分割" - split-window -v -c '#{pane_current_path}'
bind-key s choose-tree -Zw
bind-key -N "再読み込み" r {
    source-file ~/.config/tmux/tmux.conf ; \
    display-message "Reload Config!!"
}
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key -N "次のウィンドウを選択" -n C-p previous-window
bind-key -N "前のウィンドウを選択" -n C-n next-window
bind-key -N "現在のウィンドウを前に並び替え" -n C-h swap-window -t -1 \; previous-window
bind-key -N "現在のウィンドウを後ろに並び替え" -n C-l swap-window -t +1 \; next-window

bind-key -r H resize-pane -L 5
bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r L resize-pane -R 5

set-option -g base-index 1
set-option -g pane-base-index 1
set-option -g mouse on

set-option -gw mode-keys vi
set-option -s set-clipboard on
set-option -gu terminal-features
set-option -as terminal-features ",screen-256color:clipboard"
set-option -g status-right-length 190

set-option -g status-bg "colour52"
set-option -g status-fg "colour93"
set-option -g status-left  "\
#[bg=colour129]#[fg=colour255] #S:#I.#P "

set-option -g status-interval 1
set-option -g status-justify centre

set-option -g status-right "\
#[fg=colour93]#[bg=colour52]\
 #h #{?client_prefix,#[reverse],}#(tmux show-options -g prefix)#{?client_prefix,#[noreverse],} \
#[fg=colour255]#[bg=colour52]\
%Y/%m/%d(%a) %H:%M:%S"

setw -g window-status-current-format '\
#[fg=colour249]#[bg=colour234]#[bg=colour239]#[fg=colour119]\
#I#[fg=colour220]:#[fg=colour255]#W#[fg=colour249]\
#F#[fg=colour239]#[bg=colour234]'

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi V send-keys -X select-line
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key -T copy-mode-vi Y send-keys -X copy-line
bind-key -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"

bind-key -N "ファイル検索" f {
    display-popup -w 95% -h 90% -E \
    -d '#{pane_current_path}' \
    "rg --files --hidden --glob '!.git' | \
     fzf --preview 'bat --style=numbers --color=always --line-range :500 {}' | \
     xargs -r -I {} tmux send-keys 'nvim {}' Enter"
}
bind-key -N "Grep検索" G {
    display-popup -w 95% -h 90% -E \
    -d '#{pane_current_path}' \
    "fzf --bind 'change:reload:rg --line-number --no-heading --color=always --smart-case {q} || true' \
         --ansi --delimiter : \
         --preview 'bat --style=numbers --color=always --highlight-line {2} {1}' \
         --preview-window 'up,60%,border-bottom,+{2}+3/3,~3' \
    | awk -F: '{print \"+\"$2, $1}' \
    | xargs -r tmux send-keys 'nvim' Enter"
}
bind-key -N "lazygitをポップアップで開く" g {
    display-popup -w 95% -h 90% -E \
    -d '#{pane_current_path}' \
    'lazygit --use-config-dir=$HOME/.config/lazygit'
}
