export BASH_CONFIG_HOME="${XDG_CONFIG_HOME}/bash"

. "${BASH_CONFIG_HOME}/utils.bash"
. "${BASH_CONFIG_HOME}/function.bash"
. "${BASH_CONFIG_HOME}/init.bash"
. "${BASH_CONFIG_HOME}/notification.bash"

if [ -f ~/.bashrc.local ]; then
    . ~/.bashrc.local
fi
