export BASH_CONFIG_HOME="${XDG_CONFIG_HOME:-${HOME}/.config}/bash"

. "${BASH_CONFIG_HOME}/utils.bash"
. "${BASH_CONFIG_HOME}/function.bash"
. "${BASH_CONFIG_HOME}/bind.bash"
. "${BASH_CONFIG_HOME}/alias.bash"
. "${BASH_CONFIG_HOME}/init.bash"
. "${BASH_CONFIG_HOME}/notification.bash"
. "${BASH_CONFIG_HOME}/prompt.bash"

if [[ -f "${HOME}/.bashrc.local" ]]; then
  . "${HOME}/.bashrc.local"
fi
