### alias ###
alias nl='nl -ba -s ": "'
alias tree='sh ~/.scripts/tree-symbolic.sh'
alias closesns='sh ~/.scripts/macos_close_sns_apps.sh'
alias notify='sh ~/.scripts/notification.sh'
alias edit='open -a "Visual Studio Code" '
alias la='ls -A'
alias h='history'
alias h2='history 20'
alias la='ls -laO'
alias ll='ls -l'
alias cl='printf "\33c\e[3J"'
alias java_home-v='sh ~/.scripts/java_home-v.sh'
alias path='echo $PATH | tr ":" "\n"'

alias git-commit-setup='~/.config/git/scripts/setup-commit-template.sh'

source "/Users/horinakayoshiki/.deno/env"

eval "$(/Users/horinakayoshiki/.local/bin/mise activate bash)"

if [ -f ~/.bashrc.local ]; then
    source ~/.bashrc.local
fi

##
# End of .bashrc
##
