export PATH=$HOME/.progate/bin:$PATH
alias arm="exec arch -arch arm64e /bin/zsh --login"
alias x64="exec arch -arch x86_64 /bin/zsh --login"
alias nl="nl -ba -s ':  '"
alias tree="${HOME}/bin/tree.sh"
source "/Users/horinakayoshiki/.deno/env"

[[ "$TERM_PROGRAM" == "kiro" ]] && . "$(kiro --locate-shell-integration-path zsh)"
